# Generated by Django 6.0.4 on 2026-04-20 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('vehicles', '0002_vehicle_created_at_vehicle_school_vehicle_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('grade', models.CharField(max_length=20)),
                ('student_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(blank=True, limit_choices_to={'user_type': '6'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='vehicles.route')),
                ('stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments', to='vehicles.stop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'route', 'direction')},
            },
        ),
    ]
