# Generated by Django 6.0.4 on 2026-04-20 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('vehicles', '0002_vehicle_created_at_vehicle_school_vehicle_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(limit_choices_to={'user_type': '5'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.route')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='GPSPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.FloatField(default=0)),
                ('heading', models.FloatField(default=0, help_text='Degrees 0–360')),
                ('recorded_at', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='trips.trip')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('board', 'Boarded'), ('alight', 'Alighted')], max_length=6)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_checkins', to=settings.AUTH_USER_MODEL)),
                ('stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_events', to='vehicles.stop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_events', to='students.student')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_events', to='trips.trip')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('route', 'trip_date'), name='unique_route_trip_date'),
        ),
    ]
