# Generated by Django 6.0.4 on 2026-06-09 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_gpsping_latitude_alter_gpsping_longitude'),
        ('vehicles', '0003_alter_stop_latitude_alter_stop_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trip',
            name='unique_route_trip_date',
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('route', 'trip_date', 'status', 'vehicle'), name='unique_route_trip_date'),
        ),
    ]
