# Generated by Django 6.0.4 on 2026-06-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_trip_unique_route_trip_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(),
        ),
    ]
