# Generated by Django 6.0.4 on 2026-06-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_created_at_vehicle_school_vehicle_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stop',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
